import { useEffect, useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CheckCircle2, AlertOctagon, Rocket, Sparkles, ChevronDown } from "lucide-react";
import { format } from "date-fns";
import { supabase } from "@/integrations/supabase/client";

interface DeltaItem { key: string; label: string; from?: string; to?: string; message?: string }
interface SprintItem { sprint_id?: string; title: string; summary?: string; category?: string }
interface OpsPayload {
  status: "green" | "amber" | "red";
  generatedAt: string;
  failCount: number;
  warnCount: number;
  issueCount: number;
  resolved: DeltaItem[];
  opened: DeltaItem[];
  sprints: SprintItem[];
  takeaway?: string;
}
interface OpsRow {
  id: string;
  report_date: string;
  payload: OpsPayload;
  email_sent_at: string | null;
}

const STATUS_PILL = {
  green: "bg-emerald-600 text-white",
  amber: "bg-amber-600 text-white",
  red: "bg-destructive text-destructive-foreground",
} as const;

export default function DailyOpsReportCard() {
  const [today, setToday] = useState<OpsRow | null>(null);
  const [history, setHistory] = useState<OpsRow[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const [openRow, setOpenRow] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      const { data } = await supabase
        .from("daily_ops_reports")
        .select("id, report_date, payload, email_sent_at")
        .order("report_date", { ascending: false })
        .limit(14);
      const rows = (data || []) as unknown as OpsRow[];
      setHistory(rows);
      setToday(rows[0] || null);
    })();
  }, []);

  if (!today) {
    return (
      <Card className="p-6 mb-6 border-dashed">
        <div className="text-sm text-muted-foreground">
          No daily ops report yet. The first one will be generated by the next cron run (07:00 UTC).
        </div>
      </Card>
    );
  }

  const p = today.payload;
  return (
    <Card className="p-6 mb-6">
      <div className="flex items-start justify-between gap-4 mb-4">
        <div>
          <div className="text-xs uppercase tracking-wide text-muted-foreground mb-1">Daily Ops Report</div>
          <h3 className="text-lg font-bold">{format(new Date(today.report_date), "EEEE, MMM d")}</h3>
          <div className="text-xs text-muted-foreground mt-0.5">
            Generated {format(new Date(p.generatedAt), "HH:mm 'UTC'")}
            {today.email_sent_at && ` · Emailed ${format(new Date(today.email_sent_at), "HH:mm")}`}
          </div>
        </div>
        <Badge className={STATUS_PILL[p.status]}>
          {p.status.toUpperCase()} · {p.failCount} fail · {p.warnCount} warn
        </Badge>
      </div>

      {p.takeaway && (
        <div className="bg-amber-50 border-l-4 border-amber-500 p-3 mb-4 rounded-r">
          <div className="flex items-start gap-2">
            <Sparkles className="h-4 w-4 text-amber-700 mt-0.5 shrink-0" />
            <div>
              <div className="text-[11px] font-bold text-amber-700 uppercase tracking-wide">ABBY Takeaway</div>
              <div className="text-sm text-foreground mt-0.5">{p.takeaway}</div>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Section icon={<CheckCircle2 className="h-4 w-4 text-emerald-600" />} title={`Fixes resolved (${p.resolved.length})`} empty="No checks moved to OK">
          {p.resolved.map((r) => (
            <div key={r.key} className="text-sm">
              <div className="font-medium">{r.label}</div>
              <div className="text-xs text-muted-foreground">was {r.from?.toUpperCase()} → OK</div>
            </div>
          ))}
        </Section>
        <Section icon={<AlertOctagon className="h-4 w-4 text-destructive" />} title={`New issues (${p.opened.length})`} empty="No new issues opened">
          {p.opened.map((r) => (
            <div key={r.key} className="text-sm">
              <div className="font-medium">{r.label}</div>
              <div className="text-xs text-muted-foreground">now {r.to?.toUpperCase()} · {r.message}</div>
            </div>
          ))}
        </Section>
        <Section icon={<Rocket className="h-4 w-4 text-indigo-600" />} title={`Shipped (${p.sprints.length})`} empty="No sprints shipped">
          {p.sprints.map((s, i) => (
            <div key={i} className="text-sm">
              <div className="font-medium">{s.sprint_id ? `${s.sprint_id} — ` : ""}{s.title}</div>
              {s.summary && <div className="text-xs text-muted-foreground line-clamp-2">{s.summary}</div>}
            </div>
          ))}
        </Section>
      </div>

      {history.length > 1 && (
        <div className="mt-5 pt-4 border-t">
          <Button variant="ghost" size="sm" onClick={() => setShowHistory((v) => !v)} className="text-xs">
            <ChevronDown className={`h-3 w-3 mr-1 transition-transform ${showHistory ? "rotate-180" : ""}`} />
            {showHistory ? "Hide" : "Show"} 14-day history
          </Button>
          {showHistory && (
            <div className="mt-3 space-y-1">
              {history.slice(1).map((h) => (
                <div key={h.id}>
                  <button
                    onClick={() => setOpenRow(openRow === h.id ? null : h.id)}
                    className="w-full flex items-center justify-between px-3 py-2 rounded hover:bg-muted text-left text-sm"
                  >
                    <span>{format(new Date(h.report_date), "EEE, MMM d")}</span>
                    <span className="flex items-center gap-2 text-xs text-muted-foreground">
                      <Badge variant="outline" className="text-[10px]">{h.payload.status?.toUpperCase()}</Badge>
                      {h.payload.resolved?.length || 0} resolved · {h.payload.opened?.length || 0} new · {h.payload.sprints?.length || 0} shipped
                    </span>
                  </button>
                  {openRow === h.id && (
                    <pre className="text-[11px] bg-muted/50 p-3 rounded mt-1 overflow-x-auto">
                      {JSON.stringify(h.payload, null, 2)}
                    </pre>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </Card>
  );
}

function Section({ icon, title, empty, children }: { icon: React.ReactNode; title: string; empty: string; children: React.ReactNode }) {
  const arr = Array.isArray(children) ? children : [children];
  const isEmpty = arr.filter(Boolean).length === 0;
  return (
    <div className="border rounded-lg p-3 bg-card">
      <div className="flex items-center gap-2 text-xs font-semibold mb-2">
        {icon}
        <span>{title}</span>
      </div>
      {isEmpty ? (
        <div className="text-xs text-muted-foreground italic">{empty}</div>
      ) : (
        <div className="space-y-2">{children}</div>
      )}
    </div>
  );
}
