/**
 * Product-specific content for the "Behind the Design" panel.
 * Each product has 5 tabs: methodology, market, pricing, marketing, connected.
 * 
 * This is a living document — update content here as frameworks evolve.
 */

export interface BehindTheDesignData {
  methodology: string;
  market: string;
  pricing: string;
  marketing: string;
  connected: string;
}

const CONTENT: Record<string, BehindTheDesignData> = {
  // ── BUILD ──────────────────────────────────────────────
  "workbook": {
    methodology: "Abby designs your workbook using **Activity-Based Learning (ABL)** — a proven instructional method where learners engage through doing, not just reading. Every chapter of your book becomes a workbook section following the **Read → Reflect → Act** cycle, adapted from Kolb's Experiential Learning Cycle (Case Western Reserve University, 1984).\n\nResearch in Active Learning Theory shows that students who engage with material through writing, reflection, and application retain 75% more than those who only read passively (Prince, 2004, *Journal of Engineering Education*).\n\nYour workbook includes three components per chapter: a **Key Takeaway** (concise summary), **Reflection Prompts** (questions connecting content to the reader's situation), and **Action Steps** (concrete exercises to apply the learning).",
    market: "Companion workbooks in the self-help and business niche sell for $9.99–$29.99. The most successful workbooks are those tied to a specific book, because readers who already bought the book are pre-qualified buyers — they have demonstrated interest in the topic and trust in the author.\n\nWorkbooks are the easiest digital product to create because Abby extracts the exercises directly from your book's chapters. They are also the highest-converting upsell at book checkout (10–25% add-on rate).",
    pricing: "Abby prices your workbook using the **Value Ladder** model (Russell Brunson, *DotCom Secrets*). The workbook sits at the **Tripwire** tier — a low-cost entry product priced at 2–3x your book's retail price. This price point is low enough to convert first-time buyers but high enough to establish that your expertise has value beyond the book.\n\nPricing psychology: prices ending in .99 ($14.99, $19.99, $24.99) consistently outperform round numbers in conversion rate studies (Monroe, *Pricing: Making Profitable Decisions*).",
    marketing: "Abby will generate a complete marketing campaign for your workbook:\n\n• A 5-email launch sequence to your existing readers using the **Know → Like → Trust → Buy** funnel\n• Social media posts announcing the workbook with quotes and preview pages\n• An upsell offer at your book's checkout page ('Add the workbook for $14.99')\n• A free sample chapter as a lead magnet to capture new email subscribers",
    connected: "Your workbook connects to 6 other revenue streams:\n\n• **Special Editions** — included in Gift Set bundles\n• **Home Study** — daily exercises feed into the 21-day program\n• **Online Course** — becomes the printable course workbook\n• **Email Marketing** — free chapter becomes a lead magnet\n• **Upsells** — one-click add at book checkout\n• **Book Sales** — bundled with direct book purchases",
  },
  "home-study": {
    methodology: "Abby designs your Home Study program using **Habit Formation Science** based on research by Dr. Phillippa Lally at University College London (2010), which found that it takes a minimum of 21 days of consistent practice for a new behavior to become automatic.\n\nEach day follows a structured rhythm: **Learn** (5–10 min reading from your book), **Practice** (15–20 min hands-on activity), and **Reflect** (5 min journaling prompt). This structure combines **Microlearning** (short sessions improve retention by 20% over long sessions), **Deliberate Practice** (Anders Ericsson, 1993 — focused, structured practice with feedback), and **Spaced Repetition** (revisiting key concepts at increasing intervals improves long-term retention by up to 200%).\n\nTotal daily commitment: 25–35 minutes — designed to fit into any schedule.",
    market: "Self-paced accountability programs in the self-help and business niche sell for $27–$97. The 21-day format is the most popular because it aligns with the widely recognized '21-day habit' concept. 30-day programs command a slight premium ($47–$97) because of the additional depth.\n\nHome Study programs outperform ebooks 3:1 in completion rates because the daily structure creates accountability. Authors who offer Home Study programs report that completers become their most loyal customers and strongest testimonials.",
    pricing: "Abby prices your Home Study at the **Tripwire to Core** tier on the Value Ladder — $47 for 21-day programs and $67 for 30-day programs. This is approximately 3–5x your book's retail price, which is the sweet spot for first-time digital product buyers.\n\nThe pricing is based on the **Transformation Value** principle: you are not selling pages or minutes — you are selling the outcome of 21 days of guided practice. The daily accountability structure justifies a premium over a static workbook.",
    marketing: "Abby will generate:\n\n• A 7-email launch sequence targeting book buyers ('You read the book — now live it')\n• Daily check-in emails with streak tracking and milestone celebrations (Day 7, 14, 21)\n• Social media countdown posts and participant testimonials\n• A free 3-day sample as a lead magnet\n• An upsell path: Home Study completers get a discount on your Online Course",
    connected: "Your Home Study connects to 6 other revenue streams:\n\n• **Workbook** — daily exercises are the workbook in action\n• **Online Course** — graduates get a discount code for the full course\n• **Reading Club** — 100-Day Challenge readers are pre-qualified leads\n• **Email Marketing** — daily emails build engagement and trust\n• **Coaching** — completers are pre-qualified coaching leads\n• **Special Editions** — included in Gift Set bundles",
  },
  "online-course": {
    methodology: "Abby designs your course using two of the most respected frameworks in education:\n\n**Bloom's Taxonomy** (Benjamin Bloom, 1956; revised Anderson & Krathwohl, 2001) — the most widely used framework in education worldwide. Your course progresses through six cognitive levels: Remember → Understand → Apply → Analyze → Evaluate → Create. This is why your course has 7 modules — each one builds on the previous, moving students from basic comprehension to creating their own original work using your framework.\n\n**Kolb's Experiential Learning Cycle** (David Kolb, Case Western Reserve University, 1984) — every activity within every module follows four stages: Do → Think → Understand → Try Differently. This ensures students learn by doing, not just by watching videos.\n\nYour course also uses **Backward Design** (Wiggins & McTighe) — Abby starts with the transformation your students want, then designs backward to ensure every module contributes to that outcome.",
    market: "Online courses in your topic area sell for $97–$497. Self-paced recorded courses average $97–$197. Live facilitated courses with group interaction command $197–$497. Courses with a coaching add-on reach $497–$997.\n\nThe online course market is projected to reach $375 billion by 2026. Author-created courses have a unique advantage: the book serves as proof of expertise, and book readers are pre-qualified students who already trust the author's methodology.",
    pricing: "Abby prices your course using the **Value Ladder** at the **Core Offer** tier — this is your main revenue driver. The pricing follows three principles:\n\n**Anchoring:** Abby shows 'This course would cost $3,500 to build with a freelancer — your students get it for $197.' The anchor makes the price feel like a bargain.\n\n**Tiered Pricing with Decoy Effect:** Self-Paced $97 / Live $197 / Live + Coaching $297. The middle option becomes the most popular because the top option makes it look reasonable.\n\n**Launch Pricing:** Founding member discount (e.g., $97 for the first 50 students) generates early testimonials while establishing a premium positioning.",
    marketing: "Abby will generate a complete course launch system:\n\n• A free webinar that teaches one key concept and offers the course at the end (5–15% conversion rate)\n• A 7-email nurture sequence for your email list\n• A sales page with student outcomes, curriculum preview, and guarantee\n• Social media launch posts with countdown and testimonials\n• An upsell funnel: course buyers are offered coaching at checkout",
    connected: "Your Online Course connects to 10 other revenue streams:\n\n• **Workbook** — enhanced version becomes the course workbook\n• **Home Study** — lite version for price-sensitive buyers\n• **Coaching** — course graduates are pre-qualified coaching leads\n• **Webinars** — free preview drives enrollment\n• **Certification** — course is the prerequisite for certification\n• **Memberships** — alumni get discounted community access\n• **Email Marketing** — 7-email nurture sequence\n• **Social Media** — launch campaign posts\n• **Upsells** — coaching upsell at checkout\n• **Affiliates** — swipe copy for affiliate partners",
  },
  "special-editions": {
    methodology: "Abby designs your Special Editions using two psychological principles from behavioral economics:\n\n**Scarcity Marketing** (Robert Cialdini, *Influence*, 2006) — limited print runs create urgency. When people believe something is scarce, they value it more and act faster. Abby designs limited-run editions (e.g., 'Only 100 signed copies') to trigger this effect.\n\n**Occasion-Based Gifting** — predictable calendar dates (Valentine's Day, Mother's Day, Graduation, Christmas) create natural buying moments. Abby themes your editions to specific occasions so you have a marketing reason to promote throughout the year.",
    market: "Signed copies sell for $29.99–$49.99 (2–3x retail). Hardcover collector's editions sell for $49.99–$99.99. Gift sets (book + workbook + bonus content) sell for $79.99–$149.99. The premium book market is growing as readers seek meaningful, giftable editions over mass-market paperbacks.",
    pricing: "Abby prices Special Editions using **Premium Positioning** — the price reflects exclusivity, not just content. A signed copy is the same book, but the signature and limited availability transform it into a collectible. The pricing formula: base book price × 2–10x depending on edition type and extras included.",
    marketing: "Abby will generate occasion-specific campaigns:\n\n• Pre-order pages with countdown timers and limited availability badges\n• Email sequences timed to each occasion (e.g., 'The perfect Mother's Day gift for the reader in your life')\n• Social media reveal posts showing the edition design\n• Affiliate promotions with higher commissions on premium editions",
    connected: "Your Special Editions connect to 5 other revenue streams:\n\n• **Workbook** — included in Gift Set bundles\n• **Book Sales** — sold through your direct sales channel\n• **Email Marketing** — edition launches drive list growth\n• **Social Media** — reveals create shareable content\n• **Affiliates** — higher commissions attract more promoters",
  },
  "social-media": {
    methodology: "Abby designs your social media calendar using the **Content Pillar Strategy** — a framework used by agencies managing Fortune 500 accounts. She identifies 4–6 content pillars from your manuscript (the core themes your audience cares about) and rotates content across them.\n\nEvery post follows the **Hook → Value → CTA** structure: the first line stops the scroll, the body delivers a genuine insight from your book, and the closing guides the reader to the next step.\n\nAbby applies the **80/20 Rule**: 80% value-driven content (tips, insights, stories, quotes) and 20% promotional content (product launches, offers, events). This ratio builds trust while driving sales.",
    market: "Authors who post consistently (3–5 times per week) see 3–5x more engagement than those who post sporadically. The most effective content types for authors are: quotes from the book (highest shares), practical tips (highest saves), personal stories (highest comments), and behind-the-scenes content (highest engagement rate).\n\nA social media manager would charge $2,000–$5,000/month for this level of content creation. Abby generates 90 days of platform-specific content in minutes.",
    pricing: "Your social media calendar is not a product you sell — it is the engine that sells everything else. Consistent social media presence drives traffic to your website, grows your email list, and builds the authority that makes people buy your courses, coaching, and speaking services. Abby designs every post to drive toward one of your paid products.",
    marketing: "This IS the marketing plan. Abby generates:\n\n• 90 days of platform-specific posts (LinkedIn, Instagram, X, Facebook)\n• Optimal posting times based on platform best practices\n• Hashtag strategy for discoverability\n• Content mix calibrated to your goals (audience building vs. product launches)\n• Monthly themes that align with your product launch calendar",
    connected: "Your Social Media calendar connects to ALL other revenue streams — it is the primary visibility engine:\n\n• **Email Marketing** — link-in-bio drives email signups\n• **Lead Magnets** — free downloads promoted via social\n• **Special Editions** — reveals create viral content\n• **Online Course** — launch campaign posts\n• **Webinars** — registration promotion\n• **Book Sales** — direct purchase links\n• **Reading Club** — challenge updates and community posts",
  },
  "email-marketing": {
    methodology: "Abby designs your email system using the **Know → Like → Trust → Buy** funnel — the same framework used by every successful direct-response marketer from Seth Godin (*Permission Marketing*) to modern email platforms like ConvertKit and ActiveCampaign.\n\nThe sequence mirrors the natural psychology of purchasing decisions: first the reader discovers you exist (Know), then they connect with your story (Like), then they believe you can deliver results (Trust), and only then are they ready to invest (Buy). Abby writes every email in your voice, using content from your manuscript.",
    market: "Email marketing has the highest ROI of any marketing channel — $36 for every $1 spent (Litmus, 2023). Authors with email lists of 1,000+ subscribers report 5–10x more product revenue than those relying solely on social media. Your email list is the only audience you truly own — unlike social media followers, no algorithm change can take them away.",
    pricing: "Email marketing is not a product you sell — it is the system that sells all your other products. Abby designs automated sequences that sell your workbooks, courses, coaching, and events on autopilot. A professional email copywriter would charge $500–$2,000 per sequence. Abby generates your complete email system — welcome, nurture, sales, and re-engagement sequences — as part of your subscription.",
    marketing: "Abby generates 5 complete email sequences:\n\n• **Welcome sequence** (5 emails / 14 days) — introduces you and delivers immediate value\n• **Book buyer nurture** (7 emails / 30 days) — builds trust and upsells to Workbook/Home Study\n• **Product launch** (5 emails / 7 days) — for each new product you create\n• **Re-engagement** (3 emails) — wins back inactive subscribers\n• **Weekly newsletter template** — ongoing value delivery",
    connected: "Email Marketing connects to ALL other revenue streams — it is the primary sales engine:\n\n• **Lead Magnets** — lead magnets feed the email list\n• **Social Media** — drives signups via link-in-bio\n• **Webinars** — promotes registrations\n• **Online Course** — launch and nurture sequences\n• **Coaching** — application and enrollment emails\n• **Events** — promotion and follow-up sequences\n• **Reading Club** — challenge updates via email",
  },
  "website": {
    methodology: "Abby designs your website using the **Hub-and-Spoke Model** — your website is the central hub, and all other channels (social media, email, podcasts, events) are spokes driving traffic back to it. Every page is designed with **Conversion-Centered Design** principles: one primary call-to-action per page, clear visual hierarchy, and trust signals (testimonials, credentials, media logos).\n\nYour website also follows **SEO Best Practices** — Abby structures your pages with proper headings, meta descriptions, and keyword-optimized content so your author page ranks in search results.",
    market: "Authors without a professional website are invisible to event organizers, media, corporate clients, and serious buyers. A custom author website from a web designer costs $3,000–$10,000. Abby creates your complete website — book page, about page, media kit, speaking page, product catalog, and email capture — as part of your subscription.",
    pricing: "Your website is not a product you sell — it is the storefront where all transactions happen. Every product Abby builds gets a sales page on your website. Every email sequence drives traffic here. Every social media post links back here. Abby designs each page to convert visitors into subscribers and buyers.",
    marketing: "Abby designs your website with built-in marketing:\n\n• Email capture on every page (pop-up, inline form, or exit intent)\n• SEO-optimized content for organic search traffic\n• Social proof sections (testimonials, media mentions, credentials)\n• Product catalog with clear pricing and purchase buttons\n• Media kit for journalists and event organizers",
    connected: "Your Website connects to ALL other revenue streams — it is the storefront for everything:\n\n• **Book Sales** — direct purchase page\n• **Online Course** — course sales page\n• **Coaching** — 'Work with me' page\n• **Speaking** — speaker one-sheet and booking page\n• **Email Marketing** — email capture on every page\n• **Social Media** — linked from all profiles\n• **Media & PR** — press kit and media page",
  },
  "book-sales": {
    methodology: "Abby designs your direct sales channel using **Direct-to-Consumer (DTC) Sales** principles — the same approach used by brands like Warby Parker, Glossier, and Dollar Shave Club. Instead of relying solely on Amazon (which takes 30–65% of your revenue), you sell directly to readers through your own storefront and keep 85–90% of the margin.",
    market: "Authors who sell directly through their own channels report 3–5x higher margins per sale compared to Amazon. Direct sales also give you the customer's email address — which Amazon does not share. Every direct buyer becomes a lead for your courses, coaching, and events.",
    pricing: "Abby prices your direct book sales at the same retail price as Amazon — the value proposition is not a lower price but the extras: signed copies, personalized inscriptions, bonus content, and direct access to the author. Never discount your own book — it undermines your brand positioning.",
    marketing: "Abby generates:\n\n• A professional book sales page with reviews, excerpts, and author bio\n• Checkout flow with upsell offers (add Workbook, add Home Study)\n• Post-purchase email sequence welcoming the buyer to your ecosystem\n• Social media posts driving traffic to your direct sales page",
    connected: "Book Sales connects to 4 other revenue streams:\n\n• **Special Editions** — premium versions sold through the same channel\n• **Upsells** — Workbook and Home Study offered at checkout\n• **Email Marketing** — every buyer joins your email list\n• **Lead Magnets** — free chapter drives traffic to the sales page",
  },

  // ── BRIDGE ─────────────────────────────────────────────
  "audiobook": {
    methodology: "Abby designs your audiobook using **Multi-Format Content Repurposing** — transforming your written manuscript into an audio experience. Audio learning research shows a 20–30% stronger personal connection when listeners hear the author's own voice.\n\nAuthor-narrated audiobooks perform significantly better in the self-help and business categories because readers feel a direct connection to the person behind the ideas.",
    market: "The audiobook market reached $7.7B in 2024, growing 25% year-over-year. 45% of audiobook listeners are new to the format — it's a growing audience, not a cannibalization of print sales.\n\nAudiobooks sell for $14.99–$29.99 on Audible, or 1 credit ($14.95/month). Authors earn $3.43–$7.49 per sale through ACX/Audible.",
    pricing: "**Value Ladder Position:** Foundation (Parallel to Book Sales)\n\n**Revenue Model:** Royalty-based through Audible/ACX (40% exclusive, 25% non-exclusive) or direct sales through your website (85–90% margin).",
    marketing: "Abby generates:\n\n• Audio sample clips for social media (30–60 second excerpts)\n• 'Now Available in Audio' email to book buyers\n• Podcast tour: Use audiobook clips as podcast guest content\n• Social media posts with audio snippets for Instagram/TikTok",
    connected: "Your Audiobook connects to 4 other revenue streams:\n\n• **Podcast Tour** — audiobook clips used as podcast guest content\n• **Social Media** — audio snippets for Instagram/TikTok\n• **Book Sales** — cross-promotion on book listing\n• **Email Marketing** — announcement to existing subscribers",
  },
  "podcast-scripts": {
    methodology: "Abby maps your podcast tour using **Strategic Guest Appearance Mapping** — an audience overlap analysis methodology that identifies podcasts whose listeners match your ideal reader profile.\n\nA coordinated series of guest appearances on podcasts relevant to your book's topic creates a multiplied visibility effect. Abby identifies target podcasts based on audience overlap, episode topics, and host alignment with your message.",
    market: "A single podcast guest appearance drives 50–500 book sales depending on audience size. A 10-podcast tour can generate $5,000–$50,000 in book and product sales.\n\nPodcast listenership is growing 20% annually. Authors who appear on 10+ podcasts in their first 90 days sell 3x more books.",
    pricing: "**Value Ladder Position:** Free (Audience Building + Credibility)\n\n**Revenue Model:** Podcast appearances are free — the value is audience exposure, email list growth, and credibility building.",
    marketing: "Abby generates:\n\n• Podcast pitch template customized to your book\n• 10–20 target podcast list with contact info\n• Interview talking points per podcast\n• Post-appearance social media promotion templates\n• Follow-up email sequences for new listeners",
    connected: "Your Podcast Tour connects to 5 other revenue streams:\n\n• **Audiobook** — podcast clips drive audiobook sales\n• **Email Marketing** — 'Listen to my interview' emails\n• **Lead Magnets** — podcast-exclusive free download offers\n• **Book Sales** — every appearance includes a book mention\n• **Speaking** — podcast appearances lead to speaking invitations",
  },
  "webinar": {
    methodology: "Abby designs your webinars using the **Teach-Offer Model** — 45 minutes of genuine value teaching, followed by a 15-minute offer for your paid product. This model achieves a 5–15% conversion rate — the highest of any marketing channel.\n\nThe teaching builds trust and demonstrates expertise; the offer converts that trust into revenue. The structure follows a proven sequence: Problem → Agitate → Solution → Proof → Offer → Urgency.",
    market: "Average webinar attendance rate is 40–50% of registrants. Conversion rate from attendee to buyer is 5–15%. A webinar with 100 attendees selling a $197 course converts 5–15 sales = $985–$2,955 per webinar.\n\nWebinars can be recorded and replayed on autopilot, generating sales 24/7.",
    pricing: "**Value Ladder Position:** Free (Lead Generation + Sales Tool)\n\n**Revenue Model:** Webinars are free to attend — they sell your paid products (courses, coaching, memberships).",
    marketing: "Abby generates:\n\n• Webinar slide deck template\n• Registration page with countdown timer\n• 5-email promotion sequence\n• Post-webinar follow-up sequence (attendees + no-shows)\n• Replay page with CTA and urgency deadline",
    connected: "Your Webinars connect to 5 other revenue streams:\n\n• **Online Course** — webinar is the primary sales tool for courses\n• **Home Study** — webinar preview of Day 1 content\n• **Coaching** — webinar attendees are warm coaching leads\n• **Email Marketing** — webinar registrants join your email list\n• **Memberships** — webinar drives community enrollment",
  },
  "lead-magnet": {
    methodology: "Abby designs your lead magnets using the **Specificity Principle** combined with the **5-Minute Test** — a lead magnet must solve one specific problem and be consumable in under 5 minutes.\n\nDirect response research shows that checklists convert 3:1 over ebooks. The ideal lead magnet delivers an immediate 'quick win' that proves your expertise and creates desire for more.",
    market: "The best-performing lead magnets convert 20–50% of landing page visitors to subscribers. Checklists and templates outperform ebooks 3:1 for conversion rate.\n\nEach email subscriber is worth $1–$5/month in future revenue across all products. Building a list of 1,000 subscribers can generate $12,000–$60,000/year.",
    pricing: "**Value Ladder Position:** Free (Bait)\n\n**Revenue Model:** Free — the value is email addresses. The lead magnet is the entry point to your entire Value Ladder.",
    marketing: "Abby generates:\n\n• 3 lead magnet options (checklist, template, mini-guide) derived from your book\n• Landing page for each lead magnet\n• Thank-you page with immediate upsell (Workbook or Home Study)\n• Welcome email sequence triggered by download\n• Social media promotion posts",
    connected: "Your Lead Magnets connect to 5 other revenue streams:\n\n• **Email Marketing** — lead magnets feed the email list\n• **Social Media** — lead magnets promoted via social posts\n• **Webinars** — lead magnet offered as webinar bonus\n• **Website** — lead magnet popup on author website\n• **Book Sales** — free chapter drives traffic to the sales page",
  },
  "media-outreach": {
    methodology: "Abby designs your media campaigns using **Authority Positioning Through Earned Media** — a PR methodology for systematic media outreach. She generates pitch templates based on newsworthy angles from your book, builds targeted media lists, and creates follow-up sequences.\n\nEarned media (press coverage, interviews, features) is the most credible form of marketing because a third party validates your expertise.",
    market: "A single feature in a major publication can drive 1,000–10,000 book sales. Authors with 5+ media features in the first 90 days sell 3x more books than those without.\n\nA PR agency would charge $3,000–$10,000/month for media outreach. Abby generates your complete press strategy as part of your subscription.",
    pricing: "**Value Ladder Position:** Free (Credibility Building)\n\n**Revenue Model:** Media appearances are free — the value is credibility, audience reach, and social proof that enhances all other product sales.",
    marketing: "Abby generates:\n\n• Press kit (bio, headshot, book summary, interview topics)\n• 20–30 target media outlet list\n• Pitch email templates (3 angles per outlet)\n• Follow-up sequence with timing cadence\n• 'As featured in...' social proof assets",
    connected: "Your Media & PR connects to 5 other revenue streams:\n\n• **Podcast Tour** — media outreach includes podcast pitching\n• **Book Sales** — media features drive book sales\n• **Social Media** — 'As featured in...' social proof posts\n• **Keynotes** — media credibility leads to speaking invitations\n• **Consulting** — media coverage validates B2B credibility",
  },
  "affiliates": {
    methodology: "Abby structures your affiliate program using the **Pat Flynn affiliate model** — partner-driven revenue sharing with commission optimization. Affiliates (bloggers, influencers, other authors, coaches) sell your products and earn a commission.\n\nThe key to a successful affiliate program is making it easy for affiliates to succeed: providing swipe copy, graphics, and tracking links while offering competitive commissions.",
    market: "Affiliate marketing drives 15–30% of all e-commerce revenue. The average affiliate commission for digital products is 30–50%. Top affiliates can generate $1,000–$10,000/month per product.\n\nAuthors with active affiliate programs report 20–40% of their product revenue comes from affiliate referrals.",
    pricing: "**Value Ladder Position:** Distribution Channel (applies to all products)\n\n**Commission Structure:** 30% for digital products (Workbook, Home Study, Course), 15% for physical products (Book, Special Editions), 20% for services (Coaching, Memberships).",
    marketing: "Abby generates:\n\n• Affiliate signup page with program details\n• Promotional swipe files (emails, social posts, banner ads)\n• Tracking dashboard for affiliate performance\n• Monthly affiliate newsletter template\n• Commission tier incentives for top performers",
    connected: "Your Affiliate Program connects to all products:\n\n• **All Products** — affiliates can promote any product in your catalog\n• **Special Editions** — higher commission on premium editions drives affiliate enthusiasm\n• **Online Course** — course affiliates earn the highest absolute commissions\n• **Webinars** — affiliates promote your free webinars for warm leads",
  },
  "upsell": {
    methodology: "Abby designs your upsell sequences using **Post-Purchase Value Maximization** — combining Russell Brunson's Value Ladder with Cialdini's Commitment & Consistency principle. A buyer who just said 'yes' is 60–70% more likely to say 'yes' again within the next 5 minutes.\n\nThe psychology is simple: once someone makes a commitment (a purchase), they are motivated to behave consistently with that commitment by purchasing complementary products.",
    market: "Post-purchase upsells convert at 10–25% (vs. 1–3% for cold traffic). The average upsell increases order value by 30–40%.\n\nCompanies like Amazon attribute 35% of revenue to upsell and cross-sell recommendations.",
    pricing: "**Value Ladder Position:** Multiplier (increases average order value)\n\n**Pricing Rule:** Upsell price should be 30–60% of the original purchase. If someone buys a $47 Home Study, the upsell should be $19–$29 (e.g., the Workbook).",
    marketing: "Abby generates upsell sequences:\n\n• Book purchase → Workbook upsell ($14.99)\n• Workbook purchase → Home Study upsell ($47)\n• Home Study purchase → Online Course upsell ($197)\n• Course purchase → Coaching upsell ($997)\n• Post-purchase email follow-ups for declined upsells",
    connected: "Your Upsells connect to all products:\n\n• **All Products** — every product has an upsell path to the next tier\n• **Email Marketing** — abandoned upsell follow-up emails\n• **Book Sales** — upsell at direct book checkout",
  },
  "revenue-share": {
    methodology: "Abby structures your partnerships using **Strategic Partnership Frameworks** — joint venture marketing with standard 50/50 and 70/30 revenue splits. Revenue Sharing is a partnership model where you co-create or co-promote products with other authors, coaches, or organizations.\n\nThis works especially well for cross-audience products (e.g., your book + another author's course = joint workshop).",
    market: "Joint ventures between complementary authors generate 2–5x the revenue of solo launches. The standard revenue split is 50/50 for co-created products and 70/30 (creator/promoter) for promoted products.\n\nPartnership launches consistently outperform solo launches because they combine two audiences.",
    pricing: "**Value Ladder Position:** Multiplier (leverages other people's audiences)\n\n**Revenue Split:** 50/50 for co-created products, 70/30 for promotion-only partnerships.",
    marketing: "Abby generates:\n\n• Partnership proposal template\n• Revenue sharing agreement template\n• Joint webinar promotion sequence\n• Co-branded landing page template\n• Post-launch revenue reporting",
    connected: "Your Revenue Sharing connects to 4 other revenue streams:\n\n• **Webinars** — joint webinars with partners\n• **Online Course** — co-taught courses\n• **Affiliates** — revenue sharing is a deeper form of affiliate partnership\n• **Events** — co-hosted events with shared audiences",
  },

  // ── YIELD ──────────────────────────────────────────────
  "coaching": {
    methodology: "Abby designs your coaching program using the **GROW Model** — the gold standard endorsed by the International Coaching Federation (ICF). Developed by Sir John Whitmore (1992), every session follows four phases:\n\n**G**oal — What do you want to achieve?\n**R**eality — Where are you now?\n**O**ptions — What could you do?\n**W**ill — What will you commit to?\n\nThis structured approach ensures every session delivers tangible progress and keeps clients accountable.",
    market: "The coaching industry is worth $20B globally. Non-fiction author coaches charge $150–$500/hour or $997–$5,000 per 3-month package. Authors with published books charge 2–3x more than non-published coaches.\n\nThe ICF reports that 86% of coaching clients recoup their investment in coaching.",
    pricing: "**Value Ladder Position:** High-Ticket\n\n**Recommended Pricing:** $997–$5,000 per 3-month package (8–12 sessions). Single sessions: $150–$500/hour.",
    marketing: "Coaching is sold through **demonstration of expertise**: free webinars, book content, and social proof. Your book readers are pre-sold on your methodology — they just need personal application.\n\n• Convert through **Webinars** and **Email Marketing**\n• Application-based enrollment creates exclusivity\n• Testimonials from coaching clients are your most powerful marketing asset",
    connected: "Your 1-on-1 Coaching connects to 5 other revenue streams:\n\n• **Online Course** — course graduates are pre-qualified coaching leads\n• **Home Study** — completers are warm coaching prospects\n• **Group Coaching** — 1-on-1 clients can be upgraded to group coaching facilitators\n• **Masterminds** — top coaching clients graduate to masterminds\n• **Webinars** — free webinars warm up coaching prospects",
  },
  "group-coaching": {
    methodology: "Abby designs your group coaching using **Cohort-Based Peer Learning** — grounded in Albert Bandura's Social Learning Theory and Etienne Wenger's Communities of Practice.\n\nGroups of 10–20 participants meet weekly for 8–12 weeks. The power is in the community — participants learn from each other's questions, challenges, and breakthroughs. Research shows peer learning improves outcomes by 40% compared to solo learning.",
    market: "Group coaching programs sell for $297–$997 per participant. A group of 15 at $497 = $7,455 per cohort. Running 4 cohorts/year = $29,820.\n\nGroup coaching has the highest profit margin of any coaching format because your time-per-client is dramatically reduced.",
    pricing: "**Value Ladder Position:** Premium\n\n**Recommended Pricing:** $297–$997 per participant per cohort. Annual commitment: $1,997–$4,997.",
    marketing: "Position group coaching as the **'best of both worlds'** — personal attention at a fraction of 1-on-1 pricing.\n\n• Launch through **Webinars** showcasing the community aspect\n• Use FOMO: 'Only 12 spots per cohort'\n• Course graduates get priority enrollment\n• Testimonials from past cohorts drive enrollment",
    connected: "Your Group Coaching connects to 5 other revenue streams:\n\n• **Online Course** — course + group coaching bundle\n• **Memberships** — group coaching alumni join the membership community\n• **Masterminds** — top group coaching participants graduate to masterminds\n• **Coaching** — some group members upgrade to 1-on-1\n• **Retreats** — cohort reunions become retreat events",
  },
  "membership": {
    methodology: "Abby designs your membership using the **Recurring Revenue Community Model** — built on subscription economy benchmarks and retention science.\n\nMemberships provide ongoing access to your content, community, and expertise for a monthly/annual fee. The key is continuous value delivery — new content monthly, live Q&A sessions, community discussions, and member-only resources.\n\nRetention science shows that members who engage in the first 7 days are 3x more likely to stay for 6+ months.",
    market: "Author-led memberships charge $19–$97/month. Average retention is 4–8 months. A membership with 100 members at $47/month = $4,700/month = $56,400/year.\n\nThe subscription economy has grown 435% in the last decade. Recurring revenue provides predictable income — the holy grail for author-entrepreneurs.",
    pricing: "**Value Ladder Position:** Recurring Revenue (Core)\n\n**Recommended Pricing:** $27/month or $247/year (annual discount). Premium tier: $97/month with live coaching access.",
    marketing: "Memberships convert best from **existing customers** — book buyers, course students, webinar attendees.\n\n• Use free trials (7–14 days) to reduce signup friction\n• Monthly 'member spotlight' content creates social proof\n• Annual pricing reduces churn by 40%\n• Founding member pricing creates urgency",
    connected: "Your Membership connects to 5 other revenue streams:\n\n• **All Products** — membership includes discounts on all products\n• **Group Coaching** — membership is the 'lite' version of group coaching\n• **Reading Club** — reading club members are natural membership prospects\n• **Community** — membership powers the community\n• **Online Course** — course alumni get membership discounts",
  },
  "consulting": {
    methodology: "Abby structures your consulting practice using the **McKinsey Problem-Solving Framework** with ROI measurement. Unlike coaching (personal transformation), consulting delivers business outcomes — process improvements, strategy development, team training.\n\nEvery engagement follows: Diagnosis → Analysis → Recommendation → Implementation → Measurement. Your book's methodology becomes the proprietary framework you apply to client organizations.",
    market: "Author-consultants charge $2,000–$10,000/day or $10,000–$50,000 per project. Authors with published books are perceived as 3–5x more credible than non-published consultants.\n\nThe management consulting industry is worth $300B globally. Even capturing a small niche generates significant revenue.",
    pricing: "**Value Ladder Position:** High-Ticket (B2B)\n\n**Recommended Pricing:** $5,000–$15,000 per engagement. Retainer: $3,000–$10,000/month.",
    marketing: "Consulting is sold through **credibility and case studies**.\n\n• Your book establishes methodology\n• Speaking engagements demonstrate expertise\n• Client results prove ROI\n• The sales cycle is 30–90 days with decision-makers\n• LinkedIn is the primary lead generation channel",
    connected: "Your Consulting connects to 5 other revenue streams:\n\n• **Keynotes** — speaking engagements lead to consulting contracts\n• **Training Programs** — consulting often includes training components\n• **Certification** — consultants can certify client teams\n• **Licensing** — consulting reveals licensing opportunities\n• **Book Sales** — books serve as leave-behinds",
  },
  "keynotes": {
    methodology: "Abby develops your signature talks using the **Signature Talk Framework** — grounded in Joseph Campbell's Hero's Journey and Presentation Psychology.\n\nA Keynote is a 45–60 minute signature talk based on your book's core message. Abby helps you develop 3 signature talk outlines with different angles for different audiences (corporate, association, university).\n\nThe talk structure follows: Hook → Problem → Journey → Framework → Application → Call to Action.",
    market: "First-time author speakers earn $2,500–$5,000 per keynote. Established author speakers earn $10,000–$25,000+. The speaking industry is worth $2B annually.\n\nAuthors with a published book are 5x more likely to be booked as speakers than those without.",
    pricing: "**Value Ladder Position:** High-Ticket + Lead Generation\n\n**Recommended Pricing:** $5,000–$25,000 per keynote. Virtual keynotes: $2,500–$10,000.",
    marketing: "Keynotes are sold through:\n\n• Speaker bureaus (register with 3–5 bureaus)\n• Your website's speaking page with sizzle reel\n• Direct outreach to event organizers\n• Testimonials from past audiences\n• Your book serves as your demo reel",
    connected: "Your Keynotes connect to 5 other revenue streams:\n\n• **Consulting** — keynotes lead to consulting contracts\n• **Training Programs** — keynotes lead to training program sales\n• **Book Sales** — back-of-room book sales at events (200–500 copies per event)\n• **Coaching** — audience members become coaching clients\n• **Masterminds** — high-value contacts from speaking events",
  },
  "training-programs": {
    methodology: "Abby designs your training programs using the **ADDIE Model** — the U.S. military's instructional design standard used by corporate training departments worldwide: **A**nalyze → **D**esign → **D**evelop → **I**mplement → **E**valuate.\n\nEffectiveness is measured using **Kirkpatrick's 4 Levels of Evaluation**: Reaction (Did they enjoy it?), Learning (Did they learn?), Behavior (Did they change?), Results (Did the organization benefit?).\n\nYour training uses an intensive 2–3 day format grounded in Bloom's Taxonomy and Kolb's Experiential Learning Cycle.",
    market: "Corporate training programs sell for $10,000–$50,000 per engagement. The corporate training market is worth $370B globally.\n\nOrganizations are increasingly seeking external experts with published methodologies. Your book is the proof of concept.",
    pricing: "**Value Ladder Position:** High-Ticket (B2B)\n\n**Recommended Pricing:** $10,000–$50,000 per program. Per-participant pricing: $500–$2,000.",
    marketing: "Sell training programs to:\n\n• HR directors and L&D managers\n• Conference organizers seeking pre/post-conference workshops\n• Offer a free 90-minute preview workshop to demonstrate methodology\n• Use **LinkedIn** and **Consulting** relationships for lead generation\n• Provide ROI projections based on Kirkpatrick's model",
    connected: "Your Training Programs connect to 5 other revenue streams:\n\n• **Keynotes** — training is the 'deep dive' follow-up to a keynote\n• **Certification** — training participants can pursue certification\n• **Consulting** — training + consulting bundled for enterprise clients\n• **Licensing** — organizations license your training materials\n• **Book Sales** — participant copies of your book",
  },
  "masterminds": {
    methodology: "Abby structures your mastermind using the **Napoleon Hill Mastermind Principle** from *Think and Grow Rich* (1937), combined with the Vistage peer advisory model.\n\nMasterminds are small groups (8–15) of high-achieving individuals who meet regularly to share challenges, insights, and accountability. You facilitate, but the group's collective intelligence is the primary value.\n\nThe 'hot seat' format — where one member presents a challenge and the group problem-solves — is the most effective structure.",
    market: "Author-led masterminds charge $5,000–$25,000/year per member. A mastermind with 10 members at $10,000/year = $100,000/year from a single group.\n\nMasterminds have the highest retention rate of any coaching format (85%+ annual renewal).",
    pricing: "**Value Ladder Position:** Ultra-Premium\n\n**Recommended Pricing:** $5,000–$25,000/year per member. Half-day sessions quarterly: $2,500–$5,000 per session.",
    marketing: "Masterminds are **invitation-only or application-based**.\n\n• Market to your best coaching clients, course graduates, and high-engagement email subscribers\n• Scarcity is real, not manufactured — you genuinely limit the group size\n• Member testimonials are your most powerful recruiting tool\n• Annual retreats for mastermind members create deeper bonds",
    connected: "Your Masterminds connect to 5 other revenue streams:\n\n• **Group Coaching** — mastermind is the premium upgrade from group coaching\n• **Retreats** — mastermind members get priority access to retreats\n• **Consulting** — mastermind members often become consulting clients\n• **Certification** — mastermind graduates become certified practitioners\n• **Coaching** — mastermind is the pinnacle of the coaching journey",
  },
  "retreats": {
    methodology: "Abby designs your retreats using **Immersive Transformation Design** — combining experiential learning with environment design psychology.\n\nRetreats are 2–5 day immersive experiences in a curated location. They combine teaching, workshops, networking, and personal reflection in an environment removed from daily distractions.\n\nResearch shows that immersive learning environments improve retention by 65% compared to traditional settings.",
    market: "Author-led retreats charge $1,500–$5,000 per participant (excluding travel/accommodation). A retreat with 20 participants at $2,500 = $50,000 per event.\n\nRetreat attendees have the highest lifetime customer value — they typically purchase multiple additional products.",
    pricing: "**Value Ladder Position:** Premium Experience\n\n**Recommended Pricing:** $1,500–$5,000 per participant. VIP upgrades: $500–$2,000 premium for private sessions.",
    marketing: "Market retreats to your **highest-engagement audience**:\n\n• Mastermind members, coaching clients, and course graduates\n• Use FOMO (limited spots) and social proof (past attendee testimonials)\n• Aspirational imagery of the venue and experience\n• Early-bird pricing for loyal community members",
    connected: "Your Retreats connect to 5 other revenue streams:\n\n• **Masterminds** — retreats are annual events for mastermind members\n• **Coaching** — retreat attendees are warm coaching leads\n• **Certification** — retreats can include certification components\n• **Community** — retreat alumni form a tight-knit community\n• **Book Sales** — signed copies at retreat events",
  },
  "certification": {
    methodology: "Abby structures your certification using **Competency-Based Assessment** — credentialing best practices combined with a licensed IP model.\n\nCertification allows others to teach your methodology. Certified practitioners pay for training, pass an assessment, and receive a license to deliver your content to their own audiences. This is the ultimate leverage — your methodology scales without your time.",
    market: "Author certification programs charge $2,000–$10,000 per certifee. Programs with 50+ certified practitioners generate $100,000–$500,000/year in licensing fees alone.\n\nThe professional certification market is growing 15% annually as organizations seek verified expertise.",
    pricing: "**Value Ladder Position:** Ultra-Premium (Leveraged)\n\n**Recommended Pricing:** $2,000–$10,000 per certification. Annual renewal: $500–$1,000.",
    marketing: "Market certification to your **most successful students**:\n\n• Coaching clients, training program graduates, and mastermind members\n• Position it as a career advancement tool: 'Become a Certified [Your Method] Practitioner'\n• Showcase certified practitioner success stories\n• Create a directory of certified practitioners on your website",
    connected: "Your Certification connects to 5 other revenue streams:\n\n• **Online Course** — course completion is a prerequisite for certification\n• **Training Programs** — certified practitioners deliver your training programs\n• **Consulting** — certified practitioners consult using your methodology\n• **Licensing** — certification is the entry point for licensing deals\n• **Franchise** — certification graduates become franchise candidates",
  },
  "conventions": {
    methodology: "Abby designs your conventions using **Community Gathering + Multi-Speaker Event** strategy — combining event marketing with sponsorship strategy.\n\nConventions are large-scale events (100–1,000+ attendees) built around your book's topic. You're the host/headliner, with additional speakers, workshops, networking, and an expo floor.",
    market: "Author-hosted conventions charge $297–$1,997 per ticket. A convention with 300 attendees at $497 = $149,100 in ticket revenue, plus sponsor revenue.\n\nConventions also generate significant ancillary revenue from sponsors, exhibitors, and product sales.",
    pricing: "**Value Ladder Position:** Premium Event + Brand Building\n\n**Recommended Pricing:** $297–$1,997 per ticket. VIP: $997–$2,997 with exclusive access.",
    marketing: "Position your convention as the **'must-attend event'** in your niche:\n\n• Secure 2–3 headline speakers to drive registrations\n• Early-bird pricing (30% discount) creates urgency and early cash flow\n• Use **Email Marketing** for primary promotion\n• Sponsor packages generate additional revenue\n• Record sessions for online course content",
    connected: "Your Conventions connect to 5 other revenue streams:\n\n• **Keynotes** — you keynote your own convention\n• **Exhibitors** — sponsors and exhibitors pay for booth space\n• **All Products** — convention is a sales event for your entire catalog\n• **Book Sales** — back-of-room and lobby sales\n• **Certification** — announce certification at conventions",
  },
  "fundraising": {
    methodology: "Abby structures your fundraising using **Cause-Aligned Revenue Generation** — combining cause marketing with impact measurement.\n\nFund Raising uses your book and platform to raise money for causes aligned with your message. This builds goodwill, media coverage, and audience loyalty while generating revenue through charity editions, benefit events, and cause-marketing campaigns.",
    market: "87% of consumers will purchase a product because a company advocated for an issue they cared about. Charity editions and benefit events generate 15–30% more media coverage than standard launches.\n\nCause-aligned authors build stronger emotional connections with their audience.",
    pricing: "**Value Ladder Position:** Brand Building + Revenue\n\n**Revenue Model:** Percentage of sales donated to cause (typically 10–25%), or full charity events with ticket sales.",
    marketing: "Abby generates cause-aligned campaigns:\n\n• 'Help us reach our goal of $X by [date]' campaigns\n• Partner with established charities for credibility\n• Matching gifts to double impact\n• Share progress publicly to maintain momentum\n• Charity edition pre-orders with limited availability",
    connected: "Your Fund Raising connects to 4 other revenue streams:\n\n• **Special Editions** — charity editions (portion of proceeds donated)\n• **Conventions** — benefit galas and charity events\n• **Media & PR** — cause-aligned stories get more media coverage\n• **Email Marketing** — fundraising updates build engagement",
  },
  "exhibitors": {
    methodology: "Abby plans your exhibition strategy using **Trade Show Presence Strategy** — combining exhibition marketing with lead capture optimization.\n\nExhibiting at trade shows, book fairs, and industry conferences puts your book and products in front of targeted audiences. Abby identifies the most relevant events, designs your booth strategy, and creates promotional materials.",
    market: "Book fair booths cost $500–$5,000 depending on the event. Authors who exhibit at 3+ events/year sell 2–4x more books than those who don't.\n\nThe ROI comes from direct sales, media contacts, and bulk orders from corporate buyers and bookstores.",
    pricing: "**Value Ladder Position:** Distribution + Networking\n\n**Revenue Model:** Direct book sales at events, plus bulk order leads from corporate buyers and bookstores.",
    marketing: "Abby generates exhibition materials:\n\n• Booth design guidelines and signage templates\n• Lead capture forms and follow-up sequences\n• Attendee demographics analysis for target events\n• Post-event follow-up email campaign\n• Social media live-posting strategy",
    connected: "Your Exhibitions connect to 5 other revenue streams:\n\n• **Book Sales** — direct sales at events\n• **Special Editions** — signed copies sold at booth\n• **Conventions** — exhibiting at your own convention\n• **Media & PR** — press contacts at events\n• **Consulting** — corporate leads from exhibition contacts",
  },

  // Additional builder IDs
  "in-house-speaker": {
    methodology: "Abby designs your in-house speaking using the **Corporate Alignment Approach** — customizing your book's message to address the client organization's specific challenges, culture, and strategic objectives.\n\nModular talk components can be mixed and matched for different corporate audiences. Each engagement includes pre-event consultation to align your content with the organization's goals.",
    market: "Companies book 3–5 external speakers annually. Authors with published methodology command $5,000–$20,000 per engagement, with repeat bookings at 35% rate.\n\nCorporate speaking is the gateway to training programs and consulting contracts.",
    pricing: "**Value Ladder Position:** High-Ticket (B2B)\n\n**Recommended Pricing:** $3,000–$15,000 per engagement. Half-day workshops: $5,000–$20,000.",
    marketing: "Target **HR leaders, event coordinators, and C-suite executives**:\n\n• LinkedIn outreach with published book as credibility proof\n• Speaker bureaus for corporate bookings\n• Referrals from past clients (35% repeat rate)\n• Your book serves as a leave-behind that extends impact",
    connected: "Your In-House Speaking connects to 5 other revenue streams:\n\n• **Training Programs** — speaking leads to multi-day engagements\n• **Consulting** — speaking leads to strategic advisory\n• **Book Sales** — audience members purchase books\n• **Online Course** — attendees enroll in courses\n• **Keynotes** — corporate talks lead to conference keynotes",
  },
  "jv-partnerships": {
    methodology: "Abby maps your partnerships using the **Complementary Audience Strategy** — identifying authors, speakers, and experts whose audiences overlap 30–50% with yours for maximum cross-pollination.\n\nJoint venture partnerships pair you with complementary experts. Abby identifies ideal partners based on your genre, audience demographics, and product suite.",
    market: "JV partnerships generate $10,000–$100,000+ per collaboration. A partner with 5,000 engaged subscribers can drive more sales than one with 50,000 passive followers.\n\nPartnership launches consistently outperform solo launches by 2–5x.",
    pricing: "**Revenue Structure:** 50/50 revenue split for joint products, 40–50% commission for promotions, or flat fee ($2,000–$10,000) for list access.",
    marketing: "Build JV relationships through **genuine value exchange**:\n\n• Promote their products first to build goodwill\n• Offer exclusive content for their audience\n• Make the partnership easy (provide all marketing materials)\n• Joint webinars are the most effective JV format",
    connected: "Your JV Partnerships connect to 4 other revenue streams:\n\n• **Webinars** — joint webinars with partners\n• **Online Courses** — co-taught courses\n• **Revenue Sharing** — JVs evolve into revenue sharing arrangements\n• **Events** — co-hosted events with shared audiences",
  },
  "big-ticket": {
    methodology: "Abby packages your expertise using the **High-Touch Transformation Model** — premium pricing justified by personalized attention, guaranteed outcomes, and exclusive access.\n\nBig-ticket offerings serve the top 1–5% of your audience — clients who value time over money and want the fastest path to results.",
    market: "Programs at $5,000–$50,000+ serve the top 1–5% of your audience. These clients value time over money and want the fastest path to results. A single big-ticket sale can equal 100+ book sales.\n\nHigh-ticket programs have the highest profit margin and lowest refund rates.",
    pricing: "**Value Ladder Position:** Ultra-Premium\n\n**Recommended Pricing:** $5,000–$50,000 per engagement. Include 1:1 coaching, VIP experiences, done-for-you services, and lifetime access to your content library.",
    marketing: "Sell big-ticket through **personal relationships, referrals, and application processes**:\n\n• Never use buy buttons — use 'Apply Now' to maintain exclusivity\n• The sales process includes a discovery call, proposal, and onboarding experience\n• Testimonials from past big-ticket clients are essential\n• LinkedIn and speaking events are primary lead sources",
    connected: "Big-ticket clients are the pinnacle of your product suite:\n\n• They've typically purchased **Books**, completed **Courses**, participated in **Coaching**, and attended **Retreats**\n• **Consulting** — big-ticket includes consulting components\n• **Masterminds** — big-ticket clients often join masterminds",
  },
  "licensing": {
    methodology: "Abby structures your licensing deals using **Intellectual Property Monetization** — protecting your IP while maximizing distribution.\n\nYour book's methodology, frameworks, and branded content are licensed to organizations for internal use, training, or co-branded products.",
    market: "Content licensing generates $5,000–$100,000+ annually per licensee. Organizations prefer licensed, proven content over developing their own.\n\nThe licensing model provides passive income — once the deal is structured, revenue flows without your time.",
    pricing: "**Value Ladder Position:** Ultra-Premium (Leveraged)\n\n**Recommended Pricing:** $5,000–$50,000/year depending on scope, exclusivity, and organization size. Per-use fees ($50–$500 per participant) for training applications.",
    marketing: "Target **L&D departments, franchise organizations, and educational institutions**:\n\n• Your book is the proof of concept\n• Consulting engagements reveal licensing opportunities\n• Certification graduates become licensing advocates\n• Industry conferences are prime networking venues",
    connected: "Your Licensing connects to 4 other revenue streams:\n\n• **Training Programs** — licensed content extends your training\n• **Certification** — licensees become certification program sponsors\n• **Consulting** — consulting engagements reveal licensing opportunities\n• **White Label** — licensing is the foundation for white-label deals",
  },
  "community": {
    methodology: "Abby structures your community using the **Belonging + Growth Model** — combining community psychology with progressive engagement design.\n\nPeople stay in communities that make them feel seen (belonging) and help them improve (growth). Abby structures community spaces with weekly rituals, member spotlights, and progressive challenges tied to your book's methodology.",
    market: "Online communities have a 78% member retention rate when properly managed vs. 15% for passive groups. Members who participate buy 2.5x more products.\n\nCommunity-led growth is the fastest-growing acquisition strategy in the creator economy.",
    pricing: "**Value Ladder Position:** Free tier (basic discussion) + Premium tier ($9.99–$27/month with live sessions, exclusive content, and networking).",
    marketing: "Communities are **self-marketing engines**:\n\n• Satisfied members invite peers, share wins, and create user-generated content\n• Launch with a founding members cohort of 50–100\n• Weekly rituals (challenges, Q&As) drive engagement\n• Community wins become testimonials for all products",
    connected: "Your Community connects to 5 other revenue streams:\n\n• **Social Media** — community discussions surface content\n• **Coaching** — active members upgrade to coaching\n• **Online Course** — member Q&As improve your course\n• **Membership** — community powers the membership\n• **Reading Club** — community hosts reading challenges",
  },
  "white-label": {
    methodology: "Abby designs your white-label program using the **Brand Extension Model** — repackaging your proven methodology under a client's brand for their internal use or resale.\n\nAbby creates modular content that can be easily customized with different branding while maintaining your IP protection.",
    market: "White-label content licensing is a $10B+ industry. Organizations pay premium for proven, ready-to-deploy content rather than developing from scratch.\n\nWhite-label deals provide recurring revenue with minimal ongoing effort.",
    pricing: "**Value Ladder Position:** Ultra-Premium\n\n**Recommended Pricing:** $10,000–$100,000 per deal. Per-seat models ($100–$500/user) scale with the client's organization.",
    marketing: "Target **training companies, coaches, and consultants** who need proven content for their clients:\n\n• Your book establishes the methodology's credibility\n• Certification graduates become white-label candidates\n• Industry conferences are prime networking venues\n• Provide sample modules for evaluation",
    connected: "Your White Label connects to 4 other revenue streams:\n\n• **Workbook** and **Online Course** content used in white-label products\n• **Certification** — white-label clients become certification candidates\n• **Licensing** — white-label is an evolution of licensing\n• **Training Programs** — white-label training materials",
  },
  "events": {
    methodology: "Abby designs your events using **Experience Design** — combining event marketing with lead capture optimization.\n\nEvery element — from venue selection to agenda flow — serves the dual purpose of delivering value and creating shareable moments. Abby designs events that transform attendees while generating content for your marketing.",
    market: "Live events have an 85% satisfaction rate vs. 45% for virtual experiences. Event attendees spend 3x more on products than non-attendees.\n\nEvents create the strongest emotional connections with your audience.",
    pricing: "**Value Ladder Position:** Premium Experience\n\n**Recommended Pricing:** $97–$497 for day events, $497–$2,997 for multi-day. VIP upgrades ($500–$2,000 premium).",
    marketing: "Events are **relationship accelerators**:\n\n• Promote through **Email Marketing**, **Social Media**, and **Affiliate** partners\n• Early-bird pricing creates urgency and cash flow\n• Record sessions for online course content\n• Capture testimonials and photos for social proof",
    connected: "Your Events connect to 5 other revenue streams:\n\n• **Books** — back-of-room sales\n• **Coaching** — VIP upgrades include coaching\n• **Community** and **Membership** — attendees join post-event\n• **Conventions** — events scale into conventions\n• **Social Media** — event content fuels social channels",
  },
  "franchise": {
    methodology: "Abby structures your franchise using the **Replication System** — documenting every process, creating training materials, and establishing quality standards so your methodology can be delivered consistently by licensed operators.",
    market: "Franchise-model educational programs generate $500,000–$5M+ in annual system-wide revenue. Each franchisee extends your brand reach to new markets.\n\nFranchise models provide the ultimate leverage — scaling your impact without scaling your time.",
    pricing: "**Value Ladder Position:** Ultra-Premium (Maximum Leverage)\n\n**Recommended Pricing:** $10,000–$50,000 initial investment, plus 5–8% ongoing royalties.",
    marketing: "Market franchises to **successful Certification graduates**:\n\n• Position as a career advancement opportunity\n• Provide proven business models and ongoing operational support\n• Franchisee success stories are your strongest marketing\n• Industry conferences for franchise recruitment",
    connected: "Your Franchise connects to 4 other revenue streams:\n\n• **Certification** — entry point for franchisees\n• **Training Programs** — franchisees deliver your training\n• **Conventions** — franchisee success stories at events\n• **Licensing** — franchise evolves from licensing model",
  },
};

// Fallback for any unmapped product
const FALLBACK: BehindTheDesignData = {
  methodology: "Abby uses proven pedagogical and business frameworks tailored to your book's unique content and audience. Every design decision is grounded in research-backed best practices for knowledge transfer and engagement.",
  market: "Market analysis considers your genre, audience size, competitor pricing, and seasonal demand patterns to position your product for maximum impact and discoverability.",
  pricing: "Pricing is calibrated using competitive analysis, perceived value benchmarks, and your audience's willingness to pay. The goal is to maximize revenue while maintaining accessibility for your target market.",
  marketing: "Abby generates a tailored marketing campaign including email sequences, social media posts, and launch timelines. Every campaign follows the Know → Like → Trust → Buy funnel.",
  connected: "This product connects to multiple revenue streams in your author ecosystem. Each connection creates a natural upsell or cross-sell path that increases your overall revenue per reader.",
};

export function getBehindTheDesignContent(builderId: string): BehindTheDesignData {
  // Normalize common variations
  const id = builderId
    .replace("home-study-course", "home-study")
    .replace("training-program", "training-programs")
    .replace("podcast", "podcast-scripts")
    .replace("media-outreach", "media-outreach");
  return CONTENT[id] || CONTENT[builderId] || FALLBACK;
}
