import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2, FileText, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { asBlob } from "html-docx-js-typescript";
import { supabase as sharedSupabase } from "@/lib/shared-backend";

interface BusinessPlanActionsProps {
  content: string;
  bookId: string;
  bookTitle: string;
  authorId: string;
}

/** Detect if a message contains an ABBY Business Plan */
export function isBusinessPlanMessage(content: string): boolean {
  const markers = [
    "ABBY Business Plan",
    "YOUR TRANSFORMATION PROMISE",
    "STARTER PACKAGE",
    "PRO PACKAGE",
    "ENTERPRISE PACKAGE",
    "MONETIZATION MAP",
  ];
  // Must contain at least 3 of these markers
  const matches = markers.filter((m) => content.includes(m));
  return matches.length >= 3;
}

function markdownToHtml(md: string): string {
  let html = md
    // Headers
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // Bold
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    // Italic
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Ordered lists
    .replace(/^\d+\.\s+(.+)$/gm, "<li>$1</li>")
    // Unordered lists
    .replace(/^[-•]\s+(.+)$/gm, "<li>$1</li>")
    // Wrap consecutive <li> in <ul>
    .replace(/((?:<li>.*<\/li>\n?)+)/g, "<ul>$1</ul>")
    // Paragraphs (lines that aren't already HTML)
    .replace(/^(?!<[hulo])((?!<).+)$/gm, "<p>$1</p>")
    // Line breaks
    .replace(/\n\n/g, "<br/>");

  return html;
}

function generateDocxHtml(content: string, bookTitle: string): string {
  const now = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const bodyHtml = markdownToHtml(content);

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body { font-family: 'Calibri', 'Segoe UI', sans-serif; color: #1a1a1a; line-height: 1.6; padding: 40px; max-width: 800px; margin: 0 auto; }
  h1 { font-size: 26px; color: #B8860B; border-bottom: 3px solid #B8860B; padding-bottom: 12px; margin-bottom: 8px; }
  h2 { font-size: 20px; color: #333; margin-top: 28px; border-bottom: 1px solid #e0e0e0; padding-bottom: 6px; }
  h3 { font-size: 16px; color: #555; margin-top: 20px; }
  p { font-size: 13px; margin-bottom: 8px; }
  ul, ol { font-size: 13px; margin: 8px 0; padding-left: 24px; }
  li { margin-bottom: 4px; }
  strong { color: #222; }
  .highlight { background: #fdf6e3; padding: 16px; border-left: 4px solid #B8860B; margin: 16px 0; font-size: 13px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 2px solid #e0e0e0; font-size: 11px; color: #999; text-align: center; }
</style></head><body>
${bodyHtml}
<div class="footer">
  <p>Generated by Authors Bureau — AI Marketing Studio</p>
  <p>The ABBY Framework: Analyze · Build · Bridge · Yield</p>
  <p>www.authorsbureau.com · ${now}</p>
</div>
</body></html>`;
}

export default function BusinessPlanActions({
  content,
  bookId,
  bookTitle,
  authorId,
}: BusinessPlanActionsProps) {
  const [downloading, setDownloading] = useState(false);
  const [saved, setSaved] = useState(false);
  const { toast } = useToast();
  const savedRef = useRef(false);

  // Auto-save the business plan to generated_assets
  useEffect(() => {
    if (savedRef.current) return;
    savedRef.current = true;

    (async () => {
      try {
        await cloudSupabase.from("generated_assets" as any).upsert(
          {
            book_id: bookId,
            author_id: authorId,
            asset_type: "business_plan",
            content,
            updated_at: new Date().toISOString(),
          },
          { onConflict: "book_id,asset_type" }
        );
        setSaved(true);
      } catch (err) {
        console.error("Failed to save business plan:", err);
      }
    })();
  }, [bookId, authorId, content]);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const html = generateDocxHtml(content, bookTitle);
      const blob = (await asBlob(html, { orientation: "portrait" })) as Blob;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `ABBY-Business-Plan-${bookTitle.replace(/[^a-zA-Z0-9]/g, "-")}.docx`;
      a.click();
      URL.revokeObjectURL(url);
      toast({
        title: "Downloaded!",
        description: "Your ABBY Business Plan has been saved as a Word document.",
      });
    } catch (err) {
      console.error("Download failed:", err);
      toast({
        title: "Download failed",
        description: "Please try again.",
        variant: "destructive",
      });
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="mt-4 flex items-center gap-3">
      <Button
        onClick={handleDownload}
        disabled={downloading}
        variant="outline"
        size="sm"
        className="gap-2"
      >
        {downloading ? (
          <>
            <Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating…
          </>
        ) : (
          <>
            <Download className="h-3.5 w-3.5" /> Download .docx
          </>
        )}
      </Button>
      {saved && (
        <span className="flex items-center gap-1 text-[11px] text-muted-foreground">
          <Check className="h-3 w-3 text-green-500" /> Plan saved
        </span>
      )}
    </div>
  );
}
