import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Download, Loader2, Check, Crown } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { printExportHtml } from "@/lib/print-export";
import { supabase as sharedSupabase } from "@/lib/shared-backend";
import { TIERS, useAuth } from "@/hooks/useAuth";

interface BusinessPlanActionsProps {
  content: string;
  bookId: string;
  bookTitle: string;
  authorId: string;
}

/** Detect if a message contains an ABBY Business Plan */
export function isBusinessPlanMessage(content: string): boolean {
  const normalized = content.toLowerCase();

  // Legacy + current plan formats
  const markers = [
    "abby business plan",
    "your transformation promise",
    "starter package",
    "pro package",
    "enterprise package",
    "monetization map",
    "monetisation map",
    "unlock your plan",
    "section 6 — next steps",
    "section 6 - next steps",
    "subscribe to the recommended plan",
    "roi:",
    // New v2.5 format markers
    "brand products",
    "build authority",
    "yield revenue",
    "total projected revenue",
    "28-node revenue",
    "28 node revenue",
    "estimated revenue",
    "sub-phase a",
    "sub-phase b",
    "===show_full_plan===",
    "view your full 28-node",
    "show me how to unlock",
  ];

  const matchCount = markers.filter((m) => normalized.includes(m)).length;

  // Accept either rich legacy plans or current concise plan format
  return matchCount >= 2;
}

function markdownToHtml(md: string): string {
  let html = md
    // Headers
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    // Bold
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    // Italic
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    // Ordered lists
    .replace(/^\d+\.\s+(.+)$/gm, "<li>$1</li>")
    // Unordered lists
    .replace(/^[-•]\s+(.+)$/gm, "<li>$1</li>")
    // Wrap consecutive <li> in <ul>
    .replace(/((?:<li>.*<\/li>\n?)+)/g, "<ul>$1</ul>")
    // Paragraphs (lines that aren't already HTML)
    .replace(/^(?!<[hulo])((?!<).+)$/gm, "<p>$1</p>")
    // Line breaks
    .replace(/\n\n/g, "<br/>");

  return html;
}

function generateDocxHtml(content: string): string {
  const now = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const bodyHtml = markdownToHtml(content);

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body { font-family: 'Calibri', 'Segoe UI', sans-serif; color: #1a1a1a; line-height: 1.6; padding: 40px; max-width: 800px; margin: 0 auto; }
  h1 { font-size: 26px; color: #B8860B; border-bottom: 3px solid #B8860B; padding-bottom: 12px; margin-bottom: 8px; }
  h2 { font-size: 20px; color: #333; margin-top: 28px; border-bottom: 1px solid #e0e0e0; padding-bottom: 6px; }
  h3 { font-size: 16px; color: #555; margin-top: 20px; }
  p { font-size: 13px; margin-bottom: 8px; }
  ul, ol { font-size: 13px; margin: 8px 0; padding-left: 24px; }
  li { margin-bottom: 4px; }
  strong { color: #222; }
  .highlight { background: #fdf6e3; padding: 16px; border-left: 4px solid #B8860B; margin: 16px 0; font-size: 13px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 2px solid #e0e0e0; font-size: 11px; color: #999; text-align: center; }
</style></head><body>
${bodyHtml}
<div class="footer">
  <p>Generated by Authors Bureau — AI Marketing Studio</p>
  <p>The ABBY Framework: Analyze · Brand · Build · Yield</p>
  <p>www.authorsbureau.com · ${now}</p>
</div>
</body></html>`;
}

export default function BusinessPlanActions({
  content,
  bookId,
  bookTitle,
  authorId,
}: BusinessPlanActionsProps) {
  const [downloading, setDownloading] = useState(false);
  const [saved, setSaved] = useState(false);
  const [checkoutTierLoading, setCheckoutTierLoading] = useState<keyof typeof TIERS | null>(null);
  const { toast } = useToast();
  const { isPremium, isAdmin } = useAuth();
  const savedRef = useRef(false);

  // Auto-save the business plan via edge function (bypasses RLS)
  useEffect(() => {
    if (savedRef.current) return;
    savedRef.current = true;

    (async () => {
      try {
        const { data: { session } } = await sharedSupabase.auth.getSession();
        const token = session?.access_token;
        const resp = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/business-consultant`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
          },
          body: JSON.stringify({ action: "save-plan", bookId, content }),
        });
        if (resp.ok) setSaved(true);
      } catch (err) {
        console.error("Failed to save business plan:", err);
      }
    })();
  }, [bookId, authorId, content]);

  const handleSubscribe = async (tier: keyof typeof TIERS) => {
    setCheckoutTierLoading(tier);
    const popup = window.open("about:blank", "_blank");
    try {
      const { data, error } = await sharedSupabase.functions.invoke("create-checkout", {
        body: { priceId: TIERS[tier].price_id, source_platform: "authorsbureau" },
      });
      if (error) throw error;
      if (data?.url && popup) {
        popup.location.href = data.url;
      } else if (data?.url) {
        window.location.href = data.url;
      }
    } catch (err) {
      popup?.close();
      toast({
        title: "Could not start checkout",
        description: err?.message || "Please try again.",
        variant: "destructive",
      });
    } finally {
      setCheckoutTierLoading(null);
    }
  };

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const html = generateDocxHtml(content);
      printExportHtml(html, `ABBY Business Plan - ${bookTitle}`);
      toast({
        title: "Downloaded!",
        description: "Your ABBY Business Plan is ready to save as PDF.",
      });
    } catch (err) {
      console.error("Download failed:", err);
      toast({
        title: "Download failed",
        description: "Please try again.",
        variant: "destructive",
      });
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="mt-4 space-y-3">
      <div className="flex items-center gap-3 flex-wrap">
        <Button
          onClick={handleDownload}
          disabled={downloading}
          variant="outline"
          size="sm"
          className="gap-2"
        >
          {downloading ? (
            <>
              <Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating…
            </>
          ) : (
            <>
              <Download className="h-3.5 w-3.5" /> Download PDF
            </>
          )}
        </Button>
        {saved && (
          <span className="flex items-center gap-1 text-[11px] text-muted-foreground">
            <Check className="h-3 w-3 text-accent" /> Plan saved
          </span>
        )}
      </div>

      {!(isPremium || isAdmin) && (
        <div className="rounded-lg border border-border bg-muted/30 p-3">
          <p className="text-xs font-medium text-foreground mb-2 flex items-center gap-1.5">
            <Crown className="h-3.5 w-3.5 text-secondary" /> Subscribe to start building now
          </p>
          <div className="flex flex-wrap gap-2">
            {(["brand", "build", "yield"] as const).map((tierKey) => (
              <Button
                key={tierKey}
                size="sm"
                variant={tierKey === "brand" ? "default" : "outline"}
                className="gap-1.5"
                onClick={() => handleSubscribe(tierKey)}
                disabled={checkoutTierLoading !== null}
              >
                {checkoutTierLoading === tierKey ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Crown className="h-3.5 w-3.5" />
                )}
                {TIERS[tierKey].label} (${TIERS[tierKey].monthlyPrice}/mo)
              </Button>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
