import { useState, useEffect } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { FileText, Download, Loader2, ChevronDown, ChevronUp } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { printExportHtml } from "@/lib/print-export";
import { supabase as sharedSupabase } from "@/lib/shared-backend";
import MarkdownRenderer from "@/components/dashboard/MarkdownRenderer";

interface SavedBusinessPlanProps {
  bookId: string;
  bookTitle: string;
  authorId: string;
}

interface PlanSection {
  key: string;
  label: string;
  emoji: string;
  content: string;
}

function stripMarkers(text: string): string {
  return text
    .replace(/===NAV:[\w-]+===/g, "")
    .replace(/===BUILD_REQUEST===[\s\S]*?===END_BUILD_REQUEST===/g, "")
    .replace(/===SUBSCRIBE_CTA===/g, "")
    .replace(/\[STOP\]/g, "")
    .trim();
}

function extractSections(fullContent: string): PlanSection[] {
  const sections: PlanSection[] = [];
  
  const patterns: Array<{ key: string; label: string; emoji: string; regex: RegExp }> = [
    { key: "transformation", label: "Transformation Promise", emoji: "✨", regex: /(?:#{1,3}.*?TRANSFORMATION PROMISE.*?\n)([\s\S]*?)(?=\n#{1,3}|\n.*?STARTER PACKAGE|$)/i },
    { key: "brand", label: "Starter Package", emoji: "🟢", regex: /(?:#{1,3}.*?STARTER PACKAGE.*?\n)([\s\S]*?)(?=\n#{1,3}|\n.*?PRO PACKAGE|$)/i },
    { key: "build", label: "Pro Package", emoji: "🔵", regex: /(?:#{1,3}.*?PRO PACKAGE.*?\n)([\s\S]*?)(?=\n#{1,3}|\n.*?ENTERPRISE PACKAGE|$)/i },
    { key: "yield", label: "Enterprise Package", emoji: "🟣", regex: /(?:#{1,3}.*?ENTERPRISE PACKAGE.*?\n)([\s\S]*?)(?=\n#{1,3}|\n.*?MONETIZATION MAP|$)/i },
    { key: "monetization", label: "Monetization Map", emoji: "📊", regex: /(?:#{1,3}.*?MONETIZATION MAP.*?\n)([\s\S]*?)(?=\n#{1,3}|\n.*?NEXT STEPS|$)/i },
    { key: "nextsteps", label: "Next Steps", emoji: "🚀", regex: /(?:#{1,3}.*?NEXT STEPS.*?\n)([\s\S]*?)$/i },
  ];

  for (const p of patterns) {
    const match = fullContent.match(p.regex);
    if (match?.[1]?.trim()) {
      sections.push({ key: p.key, label: p.label, emoji: p.emoji, content: stripMarkers(match[1].trim()) });
    }
  }

  return sections;
}

export default function SavedBusinessPlan({ bookId, bookTitle, authorId }: SavedBusinessPlanProps) {
  const [plan, setPlan] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    (async () => {
      setLoading(true);
      try {
        const { data: { session } } = await sharedSupabase.auth.getSession();
        const token = session?.access_token;
        const resp = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/business-consultant`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}`,
          },
          body: JSON.stringify({ action: "get-plan", bookId }),
        });
        if (resp.ok) {
          const result = await resp.json();
          setPlan(result.content || null);
        }
      } catch (err) {
        console.error("Failed to load plan:", err);
      }
      setLoading(false);
    })();
  }, [bookId, authorId]);

  if (loading) return null;
  if (!plan) return null;

  const sections = extractSections(plan);
  if (sections.length === 0) return null;

  const handleDownload = async () => {
    setDownloading(true);
    try {
      // Simple markdown to HTML
      let html = stripMarkers(plan)
        .replace(/^### (.+)$/gm, "<h3>$1</h3>")
        .replace(/^## (.+)$/gm, "<h2>$1</h2>")
        .replace(/^# (.+)$/gm, "<h1>$1</h1>")
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        .replace(/\*(.+?)\*/g, "<em>$1</em>")
        .replace(/^\d+\.\s+(.+)$/gm, "<li>$1</li>")
        .replace(/^[-•]\s+(.+)$/gm, "<li>$1</li>")
        .replace(/((?:<li>.*<\/li>\n?)+)/g, "<ul>$1</ul>")
        .replace(/^(?!<[hulo])((?!<).+)$/gm, "<p>$1</p>")
        .replace(/\n\n/g, "<br/>");

      const fullHtml = `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>body{font-family:'Calibri',sans-serif;color:#1a1a1a;line-height:1.6;padding:40px;max-width:800px;margin:0 auto}h1{font-size:26px;color:#B8860B;border-bottom:3px solid #B8860B;padding-bottom:12px}h2{font-size:20px;color:#333;margin-top:28px;border-bottom:1px solid #e0e0e0;padding-bottom:6px}h3{font-size:16px;color:#555;margin-top:20px}p{font-size:13px;margin-bottom:8px}ul,ol{font-size:13px}li{margin-bottom:4px}strong{color:#222}</style></head><body>${html}
<div style="margin-top:40px;padding-top:16px;border-top:2px solid #e0e0e0;font-size:11px;color:#999;text-align:center"><p>Generated by Authors Bureau — AI Marketing Studio</p><p>The ABBY Framework: Analyze · Brand · Build · Yield</p></div></body></html>`;

      printExportHtml(fullHtml, `ABBY Business Plan - ${bookTitle}`);
      toast({ title: "Downloaded!", description: "Business plan saved as .docx" });
    } catch (error) {
      toast({ title: "Download failed", variant: "destructive" });
    }
    setDownloading(false);
  };

  return (
    <Card className="border-secondary/30 bg-gradient-to-br from-secondary/5 to-background">
      <CardContent className="p-4 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-secondary" />
            <h3 className="font-heading font-bold text-sm">Your ABBY Business Plan</h3>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" className="gap-1.5 text-xs h-7" onClick={handleDownload} disabled={downloading}>
              {downloading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Download className="h-3 w-3" />}
              .docx
            </Button>
            <Button variant="ghost" size="sm" className="h-7 w-7 p-0" onClick={() => setExpanded(!expanded)}>
              {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
            </Button>
          </div>
        </div>

        {/* Collapsed: show section chips */}
        {!expanded && (
          <div className="flex flex-wrap gap-1.5">
            {sections.map((s) => (
              <button
                key={s.key}
                onClick={() => setExpanded(true)}
                className="text-[11px] font-medium px-2.5 py-1 rounded-full bg-muted hover:bg-muted/80 transition-colors"
              >
                {s.emoji} {s.label}
              </button>
            ))}
          </div>
        )}

        {/* Expanded: tabbed view */}
        {expanded && (
          <Tabs defaultValue={sections[0]?.key} className="mt-2">
            <TabsList className="h-auto flex-wrap gap-1 bg-transparent p-0">
              {sections.map((s) => (
                <TabsTrigger
                  key={s.key}
                  value={s.key}
                  className="text-[11px] px-3 py-1.5 data-[state=active]:bg-secondary/15 data-[state=active]:text-secondary rounded-full"
                >
                  {s.emoji} {s.label}
                </TabsTrigger>
              ))}
            </TabsList>
            {sections.map((s) => (
              <TabsContent key={s.key} value={s.key} className="mt-3">
                <div className="rounded-lg bg-muted/30 p-4 max-h-[400px] overflow-y-auto">
                  <MarkdownRenderer content={s.content} />
                </div>
              </TabsContent>
            ))}
          </Tabs>
        )}
      </CardContent>
    </Card>
  );
}
